### ISSUE TITLE
Upgrade not giving feedback to player

### ISSUE THREAD

**Issue by pablogalve** [Kalima-Entertainment/Fallout_Strategy#55]
**Summary:**

**Type:**
- [ ] Game breaking, unplayable 
- [x] Bug that makes game less playable than intended 
- [ ] Aesthetic, graphical or audio bug 

**Severity:**
- [ ] Urgent 
- [ ] High 
- [ ] Medium 
- [ ] Low  

**Steps to reproduce:**

**Actual Result:**
![image](https://user-images.githubusercontent.com/30580652/82937444-74171c00-9f90-11ea-842c-3ee843e4599e.png)

**Expected Result:**
It should give some feedback to user so they know that upgrade has started

**Build:**
0.7

**Comment by christianpi4** [comment]
Comprobate
