### ISSUE TITLE
Faction Logo in the middle of the screen

### ISSUE THREAD

**Issue by pablogalve** [Kalima-Entertainment/Fallout_Strategy#7]
**Summary:**

**Type:**
- [ ] Game breaking, unplayable 
- [ ] Bug that makes game less playable than intended 
- [x] Aesthetic, graphical or audio bug 

**Severity:**
- [ ] Urgent 
- [ ] High 
- [x] Medium 
- [ ] Low  

**Steps to reproduce:**
Pause [ESC] > Main Menu > New Game > Click a Faction > Start Game

**Actual Result:**
![image](https://user-images.githubusercontent.com/30580652/78350760-00ffb380-75a6-11ea-862f-0718cf0a9058.png)

**Expected Result:**
![image](https://user-images.githubusercontent.com/30580652/78350838-1f65af00-75a6-11ea-886e-ab8879114052.png)

**Build:**
0.2

**Comment by christianpi4** [comment]
Solved Waiting to revision
