### ISSUE TITLE
Vector crash because of particles (I think)

### ISSUE THREAD

**Issue by JBGelsenorJ** [Kalima-Entertainment/Fallout_Strategy#73]
**Summary:**

**Type:**
- [X] Game breaking, unplayable 
- [ ] Bug that makes game less playable than intended 
- [ ] Aesthetic, graphical or audio bug 

**Severity:**
- [X] Urgent 
- [ ] High 
- [ ] Medium 
- [ ] Low  

**Steps to reproduce:**Play the game normally, eventually it crashes (i was looting)

**Actual Result:**Crash

**Expected Result:**No crash

**Build:**0.7
![image](https://user-images.githubusercontent.com/33731319/83186103-4961ca80-a12c-11ea-8333-72cc0ac63829.png)

**Comment by Germanins6** [comment]
GG
